---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
        mass_threshold: 20
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- spec/
