LineLength:
  Max: 120

# Adopted from https://github.com/codeclimate/codeclimate/blob/master/config/rubocop/.rubocop.yml
Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/ClassLength:
  Max: 250

# Conflicts with IntelliJ auto formatting
Style/MultilineMethodCallIndentation:
  Enabled: false

Style/CaseIndentation:
  Enabled: false